# Generated by Django 4.2.9 on 2026-06-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('restore', 'Восстановление'), ('status_change', 'Смена статуса'), ('login', 'Вход'), ('logout', 'Выход'), ('import', 'Импорт'), ('export', 'Экспорт')], max_length=30, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=100, verbose_name='Тип объекта')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Объект')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
