# Generated by Django 4.2.9 on 2026-06-05 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Производитель')),
                ('year_manufactured', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('commissioned_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('workplace', models.CharField(blank=True, max_length=100, verbose_name='Рабочее место')),
                ('assigned_brigade', models.CharField(blank=True, max_length=200, verbose_name='Бригада')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Комментарий')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
                'db_table': 'machines',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Закреплён')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Откреплён')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущее')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Закрепление оператора',
                'verbose_name_plural': 'Закрепления операторов',
                'db_table': 'machine_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='machines/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип файла')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'machine_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
                ('color', models.CharField(choices=[('green', 'Зелёный'), ('yellow', 'Жёлтый'), ('red', 'Красный'), ('gray', 'Серый'), ('blue', 'Синий')], default='gray', max_length=10, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='Требует комментарий')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус станка',
                'verbose_name_plural': 'Статусы станков',
                'db_table': 'machine_statuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Причина / Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
                'db_table': 'machine_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Тип станка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип станка',
                'verbose_name_plural': 'Типы станков',
                'db_table': 'machine_types',
                'ordering': ['name'],
            },
        ),
    ]
