# Generated by Django 4.2.9 on 2026-06-05 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='machinestatushistory',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='machines.machine', verbose_name='Станок'),
        ),
        migrations.AddField(
            model_name='machinestatushistory',
            name='new_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_to', to='machines.machinestatus', verbose_name='Новый статус'),
        ),
        migrations.AddField(
            model_name='machinestatushistory',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='machines.machinestatus', verbose_name='Предыдущий статус'),
        ),
        migrations.AddField(
            model_name='machineattachment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='machines.machine', verbose_name='Станок'),
        ),
        migrations.AddField(
            model_name='machineattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machineassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machineassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='machines.machine', verbose_name='Станок'),
        ),
        migrations.AddField(
            model_name='machineassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='machine',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_machines', to='employees.employee', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='machine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinestatus', verbose_name='Текущий статус'),
        ),
        migrations.AddField(
            model_name='machine',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinetype', verbose_name='Тип станка'),
        ),
        migrations.AddField(
            model_name='machine',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='workshops.section', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='machine',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='workshops.workshop', verbose_name='Цех'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['inventory_number'], name='machines_invento_c03415_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['deleted_at'], name='machines_deleted_3eac37_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['current_status'], name='machines_current_4d79e7_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['workshop'], name='machines_worksho_c31fd6_idx'),
        ),
    ]
