# Generated by Django 6.0.6 on 2026-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0015_repairtask_bonus_amount_repairtask_has_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_som', models.DecimalField(decimal_places=2, default=12700, max_digits=12, verbose_name="1 USD = ? so'm")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'db_table': 'exchange_rate',
            },
        ),
    ]
